// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function List(): $CancellablePromise<string[]> {
    return $Call.ByID(287741050).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ListenAddr(): $CancellablePromise<string> {
    return $Call.ByID(707727382);
}

export function Start(): $CancellablePromise<void> {
    return $Call.ByID(1640392478);
}

export function Subscribe(callback: any): $CancellablePromise<void> {
    return $Call.ByID(103217282, callback);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
