// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsActive() {
    return $Call.ByID(2504495108);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function List() {
    return $Call.ByID(287741050).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ListenAddr() {
    return $Call.ByID(707727382);
}

/**
 * @param {any} callback
 * @returns {$CancellablePromise<void>}
 */
export function Subscribe(callback) {
    return $Call.ByID(103217282, callback);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
