// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../settings/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddMCPServer adds a new MCP server configuration
 * @param {settings$0.MCPServerConfig} config
 * @returns {$CancellablePromise<void>}
 */
export function AddMCPServer(config) {
    return $Call.ByID(1611313896, config);
}

/**
 * GetClientStatus returns the status of all clients
 * @returns {$CancellablePromise<{ [_: string]: $models.ClientStatus }>}
 */
export function GetClientStatus() {
    return $Call.ByID(3377848763).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetSettings returns the current settings
 * @returns {$CancellablePromise<settings$0.Settings | null>}
 */
export function GetSettings() {
    return $Call.ByID(3884386303).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function IsActive() {
    return $Call.ByID(2504495108);
}

/**
 * @returns {$CancellablePromise<settings$0.MCPServerConfig[]>}
 */
export function List() {
    return $Call.ByID(287741050).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ListenAddr() {
    return $Call.ByID(707727382);
}

/**
 * ReloadClients reloads all clients from settings
 * @returns {$CancellablePromise<void>}
 */
export function ReloadClients() {
    return $Call.ByID(3502122629);
}

/**
 * RemoveMCPServer removes an MCP server configuration
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RemoveMCPServer(name) {
    return $Call.ByID(255493505, name);
}

/**
 * RestartClient restarts an MCP client
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RestartClient(name) {
    return $Call.ByID(3792849082, name);
}

/**
 * StartClient starts an MCP client
 * @param {settings$0.MCPServerConfig} config
 * @returns {$CancellablePromise<void>}
 */
export function StartClient(config) {
    return $Call.ByID(2765291965, config);
}

/**
 * StopClient stops an MCP client
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function StopClient(name) {
    return $Call.ByID(2947742357, name);
}

/**
 * @param {any} callback
 * @returns {$CancellablePromise<void>}
 */
export function Subscribe(callback) {
    return $Call.ByID(103217282, callback);
}

/**
 * UpdateMCPServer updates an MCP server configuration
 * @param {string} name
 * @param {settings$0.MCPServerConfig} config
 * @returns {$CancellablePromise<void>}
 */
export function UpdateMCPServer(name, config) {
    return $Call.ByID(2323123058, name, config);
}

/**
 * UpdateSettings updates the settings
 * @param {settings$0.Settings | null} settings
 * @returns {$CancellablePromise<void>}
 */
export function UpdateSettings(settings) {
    return $Call.ByID(3316702090, settings);
}

// Private type creation functions
const $$createType0 = $models.ClientStatus.createFrom;
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = settings$0.Settings.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = settings$0.MCPServerConfig.createFrom;
const $$createType5 = $Create.Array($$createType4);
