// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ClientStatus represents the status of a client
 */
export class ClientStatus {
    /**
     * Creates a new ClientStatus instance.
     * @param {Partial<ClientStatus>} [$$source = {}] - The source object to create the ClientStatus.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["connected"] = false;
        }
        if (!("tools" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tools"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {any | undefined}
             */
            this["last_error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClientStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ClientStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClientStatus(/** @type {Partial<ClientStatus>} */($$parsedSource));
    }
}
