version: '3.8'

services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
    image: mcp-bouncer-builder:latest
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=1
