// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ClientStatus represents the status of a client
 */
export class ClientStatus {
    "name": string;
    "connected": boolean;
    "tools": number;
    "last_error"?: any;
    "authorization_required": boolean;

    /** Creates a new ClientStatus instance. */
    constructor($$source: Partial<ClientStatus> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }
        if (!("tools" in $$source)) {
            this["tools"] = 0;
        }
        if (!("authorization_required" in $$source)) {
            this["authorization_required"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClientStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ClientStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClientStatus($$parsedSource as Partial<ClientStatus>);
    }
}
