steps:
  - label: ":cargo::clippy: Cargo Clippy"
    commands:
      - cargo clippy --workspace --all-targets --all-features -- -D warnings
    plugins:
      - docker-compose#v5.10.0:
          run: app
          config: .buildkite/docker-compose.yml
          progress: plain
  - label: ":cargo::rust::test_tube: Backend Tests"
    commands:
      - cargo test --workspace --all-targets
    plugins:
      - docker-compose#v5.10.0:
          run: app
          config: .buildkite/docker-compose.yml
          progress: plain

  - label: ":node::vitest: Frontend Build & Test"
    commands:
      - npm ci
      - npm run lint
      - npm run build
      - npm run test:run

    plugins:
      - docker-compose#v5.10.0:
          run: app
          config: .buildkite/docker-compose.yml
          progress: plain

  - label: ":rust::tauri: Tauri Build"
    command: |
      cargo tauri build --verbose
    plugins:
      - docker-compose#v5.10.0:
          run: app
          config: .buildkite/docker-compose.yml
          progress: plain
